; Shared config
[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001
lib_deps =
    fastled/FastLED
    tzapu/WiFiManager
    cnmat/OSC
    bblanchon/ArduinoJson
    forkineye/ESPAsyncE131
board_build.filesystem = littlefs

; Generic ESP-WROOM-32 dev board (USB-serial, WiFi only)
[env:esp32dev]
board = esp32dev
build_flags =
    -DBOARD_GENERIC_ESP32
    -DDEFAULT_LED_PIN=2

; WT32-ETH01 (ESP32 + LAN8720 Ethernet)
[env:wt32-eth01]
board = wt32-eth01
build_flags =
    -DBOARD_WT32_ETH01
    -DDEFAULT_LED_PIN=4
